### ISSUE TITLE
EVC bytecode is version 065, but runtime supports version 73.

### ISSUE THREAD

**Issue by manavgarg272** [ethanblake4/flutter_eval#67]
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return HotSwapLoader(
      uri:
          'https://storage.cloud.google.com/staging.datingcoach-61f38.appspot.com/version_xxx.evc',
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: const MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

Error facing 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: dart_eval runtime error: EVC bytecode is version 065, but runtime supports version 73.
E/flutter (15811): Try using the same version of dart_eval for compiling as the version in your application.
E/flutter (15811): #0      Runtime._load (package:dart_eval/src/eval/runtime/runtime.dart:153:7)
E/flutter (15811): #1      Runtime._setup (package:dart_eval/src/eval/runtime/runtime.dart:281:7)
E/flutter (15811): #2      Runtime.setup (package:dart_eval/src/eval/runtime/runtime.dart:271:19)
E/flutter (15811): #3      _HotSwapLoaderState._setup.<anonymous closure> (package:flutter_eval/src/flutter_eval.dart:777:18)
E/flutter (15811): #4      State.setState (package:flutter/src/widgets/framework.dart:1138:30)
E/flutter (15811): #5      _HotSwapLoaderState._setup (package:flutter_eval/src/flutter_eval.dart:770:5)
E/flutter (15811): #6      _HotSwapLoaderState._loadFromUrl (package:flutter_eval/src/flutter_eval.dart:748:7)

**Comment by ethanblake4** [comment]
You need to recompile the EVC code with the latest version of dart_eval.
