### ISSUE TITLE
I want to use code push in flutter, and i want to use extended_image, i have no idea, can you help me?

### ISSUE THREAD

**Issue by HXiaoMing** [ethanblake4/flutter_eval#68]
flutter_eval is a very good project. i study it for a time. i want to use ExtendedImage in @RuntimeOverride, but i don't know how to do? can you help me?

ExtendedImage  is a flutter package, extended_image: ^8.2.0

when run command : dart_eval compile occur error
Compiling package hot_update...
Unhandled exception:
CompileError: Cannot find import 'package:flutter/gestures.dart' (while parsing 'package:extended_image/src/editor/editor.dart') at unknown
#0      _resolveImportsAndExports.<anonymous closure> (package:dart_eval/src/eval/compiler/compiler.dart:969:16)
#1      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#2      ListIterable.toSet (dart:_internal/iterable.dart:229:18)
#3      _resolveImportsAndExports (package:dart_eval/src/eval/compiler/compiler.dart:971:12)
#4      Compiler.compileSources (package:dart_eval/src/eval/compiler/compiler.dart:322:33)
#5      Compiler.compile (package:dart_eval/src/eval/compiler/compiler.dart:164:12)
#6      cliCompile (package:dart_eval/src/eval/cli/compile.dart:126:34)
#7      main (file:///Users/tt/.pub-cache/hosted/pub.flutter-io.cn/dart_eval-0.7.3/bin/dart_eval.dart:71:5)
#8      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

code:
```
@RuntimeOverride('#myapp_main_scaffold_1')
Widget scaffoldUpdate(
    BuildContext context, int counter, void Function() _incrementCounter) {
  return Scaffold(
    body: ExtendedImage.network('an url'),
  );
}
```

can you help me to write a wrapper for ExtendedImage? how to use ExtendedImage in @RuntimeOverride?

github:
https://github.com/HXiaoMing/hot_update.git

**Comment by hieulbp** [comment]
the same, I have a problem with flutter_inappwebview
